#!/usr/bin/env python3
"""Open a pick scene in the interactive MuJoCo viewer (requires an X display).

Two modes:
  * default — load a generated ``pick_scene_*.xml`` directly into the passive
    viewer; objects drop and settle on the table while you look around.
  * ``--sim`` — start the full StretchMuJoCoSimulator with its viewer, so the
    robot and its cameras are live too.

Controls: mouse drag = rotate, scroll = zoom, right-drag = pan, Esc = quit.

Supported scenes (``--scene <name>``), each a pick_scene_<name>.xml generated by
tools/generate_pick_scenes.py with a different RoboTwin table texture and a
random, settle-verified layout of the 12 objects:
  dark     — dark wood / brown table surface
  light    — bright, pale table surface
  neutral  — plain light-gray surface
  slate    — neutral gray surface
  warm     — warm / orange-brown surface
  bright   — light neutral surface
  wood     — stock scene.xml wood surface (built live, no saved file)
  <any other name> — see ``python tools/generate_pick_scenes.py --help``

Usage (from a terminal with a display):
  uv run python examples/view_pick_scene.py                        # pick_scene_dark
  uv run python examples/view_pick_scene.py --scene warm
  uv run python examples/view_pick_scene.py --scene dark --sim
  uv run python examples/view_pick_scene.py --scene neutral --objects 071_can,035_apple
"""

from __future__ import annotations

import time
from pathlib import Path

import click
import mujoco
import mujoco.viewer
import numpy as np

from stretch_mujoco.graspgen.objects import (
    GRASP_OBJECTS_DIR,
    MODELS_DIR,
    build_grasp_scene,
    default_positions,
    place_on_table,
    table_textures,
)

PICK_SCENE_DIR = MODELS_DIR / "assets" / "pick_scene"


def _pick_scene_path(texture: str) -> Path:
    path = PICK_SCENE_DIR / f"pick_scene_{texture}.xml"
    if not path.exists():
        raise click.ClickException(
            f"scene {path.name!r} not found; run tools/generate_pick_scenes.py first. "
            f"Scenes: {sorted(p.name for p in PICK_SCENE_DIR.glob('pick_scene_*.xml'))}"
        )
    return path


@click.command()
@click.option(
    "--scene",
    "texture",
    default="dark",
    type=click.Choice(["wood"] + sorted(table_textures())),
    show_default=True,
    help="pick scene texture to view",
)
@click.option(
    "--sim",
    is_flag=True,
    help="launch the full Stretch simulator viewer instead of the static model",
)
@click.option(
    "--objects",
    default=None,
    help="comma-separated object ids to include (default: the 12 curated objects)",
)
def main(texture: str, sim: bool, objects: str | None) -> None:
    """View a pick scene in the MuJoCo viewer (needs DISPLAY)."""
    if texture == "wood":
        # wood isn't a generated scene; build it live via build_grasp_scene.
        object_names = (
            [name.strip() for name in objects.split(",") if name.strip()]
            if objects
            else [d.name for d in sorted(GRASP_OBJECTS_DIR.iterdir()) if d.is_dir()]
        )
        model = build_grasp_scene(object_names, table_texture="wood")
        place_on_table(model, default_positions(object_names))
        click.echo(f"viewing live scene: {len(object_names)} objects on wood table")
    elif sim:
        _view_full_sim(texture, objects)
        return
    else:
        model = mujoco.MjModel.from_xml_path(str(_pick_scene_path(texture)))
        click.echo(f"viewing {_pick_scene_path(texture).name}")

    data = mujoco.MjData(model)
    click.echo("controls: drag=rotate, scroll=zoom, right-drag=pan, Esc=quit")
    with mujoco.viewer.launch_passive(model, data) as viewer:
        while viewer.is_running():
            mujoco.mj_step(model, data)
            viewer.sync()


def _view_full_sim(texture: str, objects: str | None) -> None:
    from stretch_mujoco import StretchMujocoSimulator

    object_names = (
        [name.strip() for name in objects.split(",") if name.strip()]
        if objects
        else [d.name for d in sorted(GRASP_OBJECTS_DIR.iterdir()) if d.is_dir()]
    )
    model = build_grasp_scene(object_names, table_texture=texture)
    place_on_table(model, default_positions(object_names))
    sim = StretchMujocoSimulator(model=model)
    click.echo("starting simulator with viewer (close the window to quit)...")
    try:
        sim.start(show_viewer_ui=True)
        while sim.is_running():
            time.sleep(0.5)
    finally:
        if sim.is_running():
            sim.stop()


if __name__ == "__main__":
    main()
